### PR TITLE
Update the plugin

### PR DESCRIPTION
**Pull request by seekehr**
Changelog;
- Fix a gravity bug
- Update to latest current API version
- Add sneak support
- Fix formatting

### CODE REVIEW

**Comment by MrNinja008** [comment]
> Changelog;
> 
> * Fix a gravity bug
> * Update to latest current API version
> * Add sneak support
> * Fix formatting

Yo bro It is like Raiding a boat on non water block when i raid in water....

**Review by brokiem — CHANGES_REQUESTED** [review]
formatting

**Comment by seekehr** [comment]
*SMASHES KEYBOARD*

**Comment by seekehr** [comment]
why? it's unstable

**Pull request merged**
